Net/ThemeName "Gruvbox-Red-Dark"
Net/IconThemeName "Papirus-Dark"
Gtk/CursorThemeName "Simp1e-Gruvbox-Dark"
Gtk/FontName "Iosevka Nerd Font 10"
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
