#!/bin/sh

# ---
# env variables
# ...

set $mod Mod4
set $refresh_i3status killall -SIGUSR1 i3status

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# --- font (window titles and bar)
font pango:Iosevka Nerd Font 10

# --- gaps
gaps inner 8
gaps outer -4

# --- border
default_border pixel 0
default_floating_border pixel 2


# --- Color Scheme
# bg      (0x282828)
# fg      (0xfbf1c7)
# accent  (0xe25252)
