#!/bin/sh

# --- Wallpaper (feh)
exec_always --no-startup-id $HOME/.fehbg


# --- idk
# Start XDG autostart .desktop files using dex. See also
exec --no-startup-id dex --autostart --environment i3

# --- idk
# polkit auth agent?
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# --- Network Manager Applet
# (Doesn't work cause i3blocks isn't configured)
exec --no-startup-id nm-applet

# --- Compositor (picom)
exec --no-startup-id picom


# --- bar i3blocks
bar {
        status_command i3blocks
        position top
}
