#!/bin/sh

# --- Wallpaper (feh)
exec_always --no-startup-id $HOME/.fehbg


# --- idk
# Start XDG autostart .desktop files using dex. See also
exec --no-startup-id dex --autostart --environment i3

# --- idk
# polkit auth agent?
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# --- Network Manager Applet
# (Doesn't work cause i3blocks isn't configured)
exec --no-startup-id nm-applet

# --- Compositor (picom)
exec --no-startup-id picom

# --- Hide Bar Automatically
exec --no-startup-id $HOME/.config/i3/scripts/auto-hide-bar.sh

# --- extra keybinds I think?
exec --no-startup-id sxhkd

# --- bar i3blocks
bar {
  status_command i3blocks
  position top
  modifier Mod3
  mode hide
  hidden_state hide

  colors {
    background #282828AA
    statusline #ebdbb2
    separator  #504945

    #                    border  backgr. text
    focused_workspace     #fabd2f #282828 #fabd2f
    active_workspace      #504945 #3c3836 #d5c4a1
    inactive_workspace    #282828 #282828 #665c54
    urgent_workspace      #fb4934 #fb4934 #282828
    binding_mode          #fb4934 #282828 #fb4934
  }
}
