[FileDialog]
history=file:///home/afonso/.themes, file:///home/afonso/.local/share/PrismLauncher, file:///home/afonso/Downloads
lastVisited=file:///home/afonso/Downloads
qtVersion=6.11.1
shortcuts=file:///home/afonso/Desktop, file:///home/afonso, file:///home/afonso/Downloads, file:///home/afonso/Documents, file:mods
sidebarWidth=114
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2\x8f\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x1T\0\0\0\x1\0\0\0\0\0\0\0T\0\0\0\x1\0\0\0\0\0\0\0U\0\0\0\x1\0\0\0\0\0\0\0\x92\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)
viewMode=Detail
