[Preset.Click Interval]
Millisecs=100

[Preset.More Options]
Use Custom Location=false
Use Random Interval=true
Random Interval ms=50
Use Hold Time=true
Hold Time ms=3

[Options]
SAFEMODE=true
USE_XEVENT=false
